<a href="https://colab.research.google.com/github/akiumiann/googlecolab/blob/main/Krylov%E9%83%A8%E5%88%86%E7%A9%BA%E9%96%93%E8%A7%A3%E6%B3%95(%E6%94%B9%E8%89%AF).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

第 2 問 (前回と同じ問題を疎行列 A の特徴を使って改良した連立 1 次方程式の Krylov 部分空間解法)

In [ ]:
def ConjugateGradientMethod(a,b1,c,d,e,f,g,h,i):
  N = 9
  A = np.zeros((N, N))
  for i in range(N):
   A[i, i] = 4.0
  for i in range(N-1):
   A[i, i+1] = -1.0
   A[i+1, i] = -1.0
  Ad = np.zeros((N, N))
  Au = np.zeros((N, N))
  Al = np.zeros((N, N))
  for i in range(N):
   Ad[i, i] = 4.0
  for i in range(N-1):
   Au[i, i+1] = -1.0
   Al[i+1, i] = -1.0

  print(Ad)
  print(Au)
  print(Al)

  bT = np.array([3,2,2,2,2,2,2,2,3])

  b = bT.T
  x0T = np.array([0,0,0,0,0,0,0,0,0])
  x0 = x0T.T
  xnT = np.array([0,0,0,0,0,0,0,0,0])
  xn = xnT.T
  rnT = np.array([a,b1,c,d,e,f,g,h,i])
  rn = rnT.T
  pnT = np.array([a,b1,c,d,e,f,g,h,i])
  pn = pnT.T
  r0T = bT - A@x0
  p0T = r0T
  r0 = r0T.T
  p0 = p0T.T
  q1 = np.zeros(N)
  q2 = np.zeros(N)
  q3 = np.zeros(N)

  for k in range (100):
    for j in range(N):
     q1[j] = np.array(Ad[j,j]*p0[j])
    for j in range(N-1):
     q2[j] = np.array(Au[j, j+1]*p0[j+1])
     q3[j+1] = np.array(Al[j+1, j]*p0[j])
    q0 = q1 + q2 + q3
    a0 = (r0T@p0)/(p0T@q0)
    #print('q',q1.T)
    #print('q',q2)
    #print('q',q3)
    print('q',q0)
    x0 = a0*p0
    x0T = x0.T
    x0T = x0T + xn
    #print('x0T',x0T)
    rn = r0 - a0*q0
    #print('rn',rn)
    if abs(all(rn < 1.0e-6)):
        print('Converged! Iterations = ', k)
        break
    rnT = rn.T
    r0T = r0.T
    #print('rnT',rnT)
    b0 = (rnT@rn)/(r0T@r0)
    pn = rn + b0*p0
    pnT = pn.T
    p0 = pn
    r0 = rn
    p0T = pnT
    r0T = rnT
    xn = x0T

  return x0T

In [ ]:
ConjugateGradientMethod(1,2,3,4,5,6,7,8,9)

[[4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4.]]
[[ 0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.]]
q [10.  3.  4.  4.  4.  4

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])