<a href="https://colab.research.google.com/github/akiumiann/googlecolab/blob/main/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%88%E3%83%B3%E6%B3%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

第 1 問 (ニュートン法の発展)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
#求めたい方程式
def fx(x):
  y = np.tan(x) + 0.2*x + 0.3
  return y

#微分した方程式
def df_1(a):
  dfdx = 1/np.cos(a)**2 + 0.2
  return dfdx

#ニュートン法
def calc_x0_Newton_method(x1):
  for i in range (1000):
    x0 = x1 - fx(x1)/df_1(x1)
    if abs(x1 - x0) < 1.e-6:
        print('Converged! Iterations = ', i)
        break
    x1 = x0
  return x0

#メイン実行部
x_ini = 10
calc_x0_Newton_method(x_ini)

Converged! Iterations =  5


8.324739243431686

In [ ]:
x_ini = 5
calc_x0_Newton_method(x_ini)

Converged! Iterations =  5


5.34337965077286

In [ ]:
x_ini = 100
calc_x0_Newton_method(x_ini)

Converged! Iterations =  18


26.877940724672047

f(x)がtan(x)なのでg(x)との交点が無限に存在する．
よって，適当に定める値を変えることでニュートン法を使った時のx0の値が変わることが分かった．

第 2 問 f(x) = x
5 − 7x
4 + 16x
3 − 8x
2 − 16x + 16 = 0

In [ ]:
#求めたい方程式
def fx2(x):
  y = x**5 - 7*x**4 + 16*x**3 - 8*x**2 - 16*x + 16
  return y

#解
z = []
z = np.roots([1,-7,16,-8,-16,16])
print(z)

#微分した方程式
def df_2(a):
  dfdx = 5*a**4 - 28*a**3 + 48*a**2 - 16*a -16
  return dfdx

#ニュートン法
def calc_x0_Newton_method(x1):
  for i in range (1000):
    x0 = x1 - fx2(x1)/df_2(x1)
    if abs(x1 - x0) < 1.e-6:
        print('Converged! Iterations = ', i)
        break
    x1 = x0
  return x0
#メイン実行部


[-1.        +0.j          2.00026461+0.j          1.99999997+0.00026459j
  1.99999997-0.00026459j  1.99973544+0.j        ]


In [ ]:
x_ini = 2000
calc_x0_Newton_method(x_ini)

Converged! Iterations =  70


2.000181799490002

In [ ]:
x_ini = 10
calc_x0_Newton_method(x_ini)

Converged! Iterations =  65


1.9997559460220404

In [ ]:
x_ini = -100
calc_x0_Newton_method(x_ini)

Converged! Iterations =  21


-1.000000000000008

どの値で試しても，だいたい-1か2に定まることが分かった．
また，numpyの根を求めるプログラムを使っても-1と2になることが分かった．
適当に定める値が大きいほど，収束に時間がかかった．2から値が離れているからだと考える．

第 3 問 ガウスの消去法のプログラム

In [ ]:
def Gauss_elimination(A, b, N):
  # 前進消去(上三角行列)
  for i in range(N):
    diag = A[i, i] # 対角成分を入手(diagonal)
    A[i, 0:N] = A[i, 0:N]/diag # 行列Aの(i+1)行の要素すべてをdiagで割る
    b[i] = b[i]/diag # bの(i+1)行目も忘れずに
    for k in range(i+1, N):
      p = A[k, i]
      A[k, 0:N] -= p * A[i, 0:N] # 定数倍を引く
      b[k] -= p * b[i] # bも上と同様に
  # 後退代入
  for i in range(N-1, 0, -1): # reversed(range(N))でもよい
    # N行目から解を求める
    for j in range(i):
      b[j] -= A[j, i] * b[i] / A[i, i] # 解が求まったところから更新する

  return A, b

In [ ]:
A = np.array([[1,2,1], [3,8,7], [2,7,4]])
b = np.array([3,5,8]) # 横ベクトルなので注意
N = 3
[A, b] = Gauss_elimination(A, b, N)
print(A)
print(b)

[[1 2 1]
 [0 1 2]
 [0 0 1]]
[ 1  2 -2]


In [ ]:
# A,bを再定義
A = np.array([[1,2,1], [3,8,7], [2,7,4]])
b = np.array([3,5,8]) # 横ベクトルなので注意

np.dot(np.linalg.inv(A), b)

array([ 1.,  2., -2.])