<a href="https://colab.research.google.com/github/akiumiann/googlecolab/blob/main/%E9%80%A3%E7%AB%8B1%E6%AC%A1%E6%96%B9%E7%A8%8B%E5%BC%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

第 2 問 (連立 1 次方程式の直接解法)


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import cholesky

In [ ]:
A = np.array([
    [2,1,-1],
    [1,3,1],
    [-1,1,4]
])

print(A.T) #転置行列

d00 = A[0,0]
l10 = A[1,0]/d00
d11 = A[1,1] - A[0,1]*l10
l20 = A[2,0]/d00
l21 = (A[1,2]-d00*l20*l10)/d11
d22 = A[2,2] - A[2,0]*l20 - (A[1,2]-A[0,2]*l10)*l21

L = np.array([
    [1,0,0],
    [l10,1,0],
    [l20,l21,1]
])

D = np.array([
    [d00,0,0],
    [0,d11,0],
    [0,0,d22]
])

LT = L.T

print('L=')
print(L)
print('D=')
print(D)
print('LT=')
print(LT)

A = L@D@L.T
print(A)

[[ 2  1 -1]
 [ 1  3  1]
 [-1  1  4]]
L=
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5  0.6  1. ]]
D=
[[2.  0.  0. ]
 [0.  2.5 0. ]
 [0.  0.  2.6]]
LT=
[[ 1.   0.5 -0.5]
 [ 0.   1.   0.6]
 [ 0.   0.   1. ]]
[[ 2.  1. -1.]
 [ 1.  3.  1.]
 [-1.  1.  4.]]


第 3 問 (連立１次方程式の反復解法)

In [ ]:
x0T = np.array([
    [0,0,0,0,0,0,0,0,0]
])

x0 = x0T.T

A = np.array([
    [4,-1,0,0,0,0,0,0,0],
    [-1,4,-1,0,0,0,0,0,0],
    [0,-1,4,-1,0,0,0,0,0],
    [0,0,-1,4,-1,0,0,0,0],
    [0,0,0,-1,4,-1,0,0,0],
    [0,0,0,0,-1,4,-1,0,0],
    [0,0,0,0,0,-1,4,-1,0],
    [0,0,0,0,0,0,-1,4,-1],
    [0,0,0,0,0,0,0,-1,4]
])

bT = np.array([
    [3,2,2,2,2,2,2,2,3]
])

b = bT.T

Au = np.array([
    [0,-1,0,0,0,0,0,0,0],
    [0,0,-1,0,0,0,0,0,0],
    [0,0,0,-1,0,0,0,0,0],
    [0,0,0,0,-1,0,0,0,0],
    [0,0,0,0,0,-1,0,0,0],
    [0,0,0,0,0,0,-1,0,0],
    [0,0,0,0,0,0,0,-1,0],
    [0,0,0,0,0,0,0,0,-1],
    [0,0,0,0,0,0,0,0,0]
])

AD = np.array([
    [4,0,0,0,0,0,0,0,0],
    [0,4,0,0,0,0,0,0,0],
    [0,0,4,0,0,0,0,0,0],
    [0,0,0,4,0,0,0,0,0],
    [0,0,0,0,4,0,0,0,0],
    [0,0,0,0,0,4,0,0,0],
    [0,0,0,0,0,0,4,0,0],
    [0,0,0,0,0,0,0,4,0],
    [0,0,0,0,0,0,0,0,4]
])

AL = np.array([
    [0,0,0,0,0,0,0,0,0],
    [-1,0,0,0,0,0,0,0,0],
    [0,-1,0,0,0,0,0,0,0],
    [0,0,-1,0,0,0,0,0,0],
    [0,0,0,-1,0,0,0,0,0],
    [0,0,0,0,-1,0,0,0,0],
    [0,0,0,0,0,-1,0,0,0],
    [0,0,0,0,0,0,-1,0,0],
    [0,0,0,0,0,0,0,-1,0]
])

ADr = np.linalg.inv(AD)
AuL = -(Au + AL)

for i in range(1000) :
  AuLx0 = np.dot(AuL, x0)
  AuLx0b = AuLx0 + b
  x1 = np.dot(ADr, AuLx0b)
  if abs(all(x1-x0)) < 1.0e-6:
    print('Converged! Iterations = ', i)
    break
  x0 = x1

print(x0)

Converged! Iterations =  49
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
gaussian_elimination(A, b)

[array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.])]

反復法の方は1回の精度が低く，何度も計算を繰り返すことによって近い値が出ることが分かった．

精度は両方とも1になったので，精度に違いはみられなかった．だが，収束条件を決めて途中でbreakしてる反復法の方が精度は低いと考えられる．

直接法：1回
反復法：49回